// <auto-generated />
using System;
using GeneralStore.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeneralStore.Api.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20200420163431_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeneralStore.Api.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42727d34-66d1-41da-9f5b-6991b869d140"),
                            Name = "Timmy"
                        },
                        new
                        {
                            Id = new Guid("6ced6baf-1da9-499b-96c2-db3f6e3cf062"),
                            Name = "Papierex"
                        });
                });

            modelBuilder.Entity("GeneralStore.Api.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e64a226-43df-487e-aeae-883f40cab282"),
                            Description = "Very good, very fast",
                            ManufacturerId = new Guid("42727d34-66d1-41da-9f5b-6991b869d140"),
                            Name = "Toy car",
                            Price = 120.0m
                        },
                        new
                        {
                            Id = new Guid("4864203a-f343-4f51-ad6a-edeffe2bc77c"),
                            Description = "Very pretty doll",
                            ManufacturerId = new Guid("42727d34-66d1-41da-9f5b-6991b869d140"),
                            Name = "Doll",
                            Price = 15.5m
                        },
                        new
                        {
                            Id = new Guid("acb091e9-3440-4e1b-8c72-3f7d07ffdb45"),
                            Description = "White paper for printers",
                            ManufacturerId = new Guid("6ced6baf-1da9-499b-96c2-db3f6e3cf062"),
                            Name = "500 paper sheets",
                            Price = 40m
                        },
                        new
                        {
                            Id = new Guid("e8aab2b0-3092-4b63-a128-41730f06cb80"),
                            Description = "Pretty notepad with 60 pages",
                            ManufacturerId = new Guid("6ced6baf-1da9-499b-96c2-db3f6e3cf062"),
                            Name = "Pretty A4 notepad",
                            Price = 20m
                        },
                        new
                        {
                            Id = new Guid("53ce0364-8501-447d-953b-5a24f9a99a8d"),
                            Description = "Cheap A4 notepad, 50 pages",
                            ManufacturerId = new Guid("6ced6baf-1da9-499b-96c2-db3f6e3cf062"),
                            Name = "Ugly, but cheap A4 notepad",
                            Price = 8m
                        });
                });

            modelBuilder.Entity("GeneralStore.Api.Entities.Product", b =>
                {
                    b.HasOne("GeneralStore.Api.Entities.Manufacturer", "Manufacturer")
                        .WithMany("ManufacturedProducts")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
